on:
  workflow_dispatch:

name: Validate, generate and publish registry

jobs:
  upload-registry:
    name: Upload to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-save

      - name: Validate schema
        run: bun validate:schema

      - name: Generate registry types
        run: bun generate:types

      - name: Validate logic
        run: bun validate:networks

      - name: Generate registry
        run: bun generate:public

      - name: Validate registry
        run: bun validate:public

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=graphregistry

    env:
      THEGRAPH_STUDIO_KEY: ${{ secrets.THEGRAPH_STUDIO_KEY }}
      REGISTRY_ROOT_URL: "https://graphregistry.pages.dev"
