on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

name: Validate, generate and publish registry

jobs:
  upload-registry:
    name: Upload to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-save

      - name: Validate schema
        run: bun validate:schema

      - name: Generate registry types
        run: bun generate:types

      - name: Validate logic
        run: bun validate:networks

      - name: Generate registry
        run: bun generate:public

      - name: Validate registry
        run: bun validate:public

      - name: Format
        run: bun format

      - name: Get version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "REGISTRY_VERSION=v${VERSION}" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="${{ env.REGISTRY_VERSION }}"
          if git fetch --tags && git tag -l | grep -q "$TAG"; then
            echo "Error: Registry $TAG already exists. Bump up the version in package.json to publish"
            exit 1
          fi

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=graphregistry

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add .
          git commit -m "generate registry ${{ env.REGISTRY_VERSION }}" || echo "No changes to commit"
          git push origin main

      - name: Create tag and publish release
        run: |
          TAG="${{ env.REGISTRY_VERSION }}"
          git tag "$TAG"
          git push origin "$TAG"

          RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"tag_name\": \"$TAG\", \"name\": \"$TAG\", \"body\": \"${TAG}: ${{ env.REGISTRY_ROOT_URL }}/TheGraphNetworksRegistry_v0_x_x.json\"}" \
          "$RELEASE_URL"
    env:
      THEGRAPH_STUDIO_KEY: ${{ secrets.THEGRAPH_STUDIO_KEY }}
      REGISTRY_ROOT_URL: "https://graphregistry.pages.dev"
